//ap definitions
#ifndef AP_DEFS_H
#define AP_DEFS_H

typedef enum
{
	AP_KEYGEM_RED = 0,
	AP_KEYGEM_YELLOW = 1,
	AP_KEYGEM_BLUE = 2,
	AP_KEYGEM_GREEN = 3,
	AP_EXTRA_LIFE = 10,
	AP_STUNNER_AMMO = 11
} AP_ItemId;

typedef enum //to enforce uniqueness, this is the to product of level id and the constant 3, plus the episode number
{
	AP_LEVEL_SLUG_VILLAGE = 7,
	AP_LEVEL_BORDER_VILLAGE = 10,
	AP_LEVEL_THE_PERILOUS_PIT = 13,
	AP_LEVEL_CAVE_OF_THE_DESCENDENTS = 16,
	AP_LEVEL_CHASM_OF_CHILLS = 19,
	AP_LEVEL_CRYSTALUS = 22,
	AP_LEVEL_HILVILLE = 25,
	AP_LEVEL_SAND_YEGO = 28,
	AP_LEVEL_MIRAGIA = 31,
	AP_LEVEL_LIFEWATER_OASIS = 34,
	AP_LEVEL_PYRAMID_OF_THE_MOONS = 37,
	AP_LEVEL_PYRAMID_OF_SHADOWS = 40,
	AP_LEVEL_PYRAMID_OF_THE_GNOSTICENE_ANCEINTS = 43,
	AP_LEVEL_PYRAMID_OF_THE_FORBIDDEN = 46,
	AP_LEVEL_ISLE_OF_TAR = 49,
	AP_LEVEL_ISLE_OF_FIRE = 52,
	AP_LEVEL_WELL_OF_WISHES = 55,
	AP_LEVEL_BEAN_WITH_BACON_MEGAROCKET = 58
} AP_CK4_LevelId;

typedef enum
{
	AP_LEVEL_ION_VENTILATION_SYSTEM = 8,
	AP_LEVEL_SECURITY_CENTER = 11,
	AP_LEVEL_DEFENSE_TUNNEL_VLOOK = 14,
	AP_LEVEL_ENERGY_FLOW_SYSTEMS = 17,
	AP_LEVEL_DEFENSE_TUNNEL_BURRH = 20,
	AP_LEVEL_REGULATION_CONTROL_CENTER = 23,
	AP_LEVEL_DEFENSE_TUNNEL_SORRA = 26,
	AP_LEVEL_NEUTRINO_BURST_INJECTOR = 29,
	AP_LEVEL_DEFENSE_TUNNEL_TELN = 32,
	AP_LEVEL_BROWNIAN_MOTION_INDUCER = 35,
	AP_LEVEL_GRAVITATIONAL_DAMPING_HUB = 38,
	AP_LEVEL_QUANTUM_EXPLOSION_DYNAMO = 41
} AP_CK5_LevelId;

typedef enum
{
	AP_POINTS_BORDER_VILLAGE = 8600,
	AP_POINTS_SLUG_VILLAGE = 33800,
	AP_POINTS_THE_PERILOUS_PIT = 18100,
	AP_POINTS_CAVE_OF_THE_DESCENDENTS = 81900,
	AP_POINTS_CHASM_OF_CHILLS = 57100,
	AP_POINTS_CRYSTALUS = 89100,
	AP_POINTS_HILVILLE = 33100,
	AP_POINTS_SAND_YEGO = 56900,
	AP_POINTS_MIRAGIA = 54500,
	AP_POINTS_LIFEWATER_OASIS = 21100,
	AP_POINTS_PYRAMID_OF_THE_MOONS = 63500,
	AP_POINTS_PYRAMID_OF_SHADOWS = 33000,
	AP_POINTS_PYRAMID_OF_THE_GNOSTICENE_ANCEINTS = 21800,
	AP_POINTS_PYRAMID_OF_THE_FORBIDDEN = 77300,
	AP_POINTS_ISLE_OF_TAR = 28800,
	AP_POINTS_ISLE_OF_FIRE = 38000,
	AP_POINTS_WELL_OF_WISHES = 20600,
	AP_POINTS_BEAN_WITH_BACON_MEGAROCKET = 0
} AP_CK4_MaxPoints;

typedef enum
{
	AP_POINTS_ION_VENTILATION_SYSTEM = 14800,
	AP_POINTS_SECURITY_CENTER = 210600,
	AP_POINTS_DEFENSE_TUNNEL_VLOOK = 98400,
	AP_POINTS_ENERGY_FLOW_SYSTEMS = 136000,
	AP_POINTS_DEFENSE_TUNNEL_BURRH = 81100,
	AP_POINTS_REGULATION_CONTROL_CENTER = 73200,
	AP_POINTS_DEFENSE_TUNNEL_SORRA = 104600,
	AP_POINTS_NEUTRINO_BURST_INJECTOR = 103700,
	AP_POINTS_DEFENSE_TUNNEL_TELN = 101200,
	AP_POINTS_BROWNIAN_MOTION_INDUCER = 100700,
	AP_POINTS_GRAVITATIONAL_DAMPING_HUB = 158700,
	AP_POINTS_QUANTUM_EXPLOSION_DYNAMO = 87300
} AP_CK5_MaxPoints;

#endif