//ap definitions
#ifndef AP_DEFS_H
#define AP_DEFS_H

typedef enum
{
	AP_KEYGEM_RED = 0,
	AP_KEYGEM_YELLOW = 1,
	AP_KEYGEM_BLUE = 2,
	AP_KEYGEM_GREEN = 3,
	AP_EXTRA_LIFE = 10,
	AP_BLASTER_SHOT = 11
} AP_ItemId;

typedef enum
{
	AP_LEVEL_SLUG_VILLAGE = 1,
	AP_LEVEL_BORDER_VILLAGE = 2,
	AP_LEVEL_THE_PERILOUS_PIT = 3,
	AP_LEVEL_CAVE_OF_THE_DESCENDENTS = 4,
	AP_LEVEL_CHASM_OF_CHILLS = 5,
	AP_LEVEL_CRYSTALUS = 6,
	AP_LEVEL_HILVILLE = 7,
	AP_LEVEL_SAND_YEGO = 8,
	AP_LEVEL_MIRAGIA = 9,
	AP_LEVEL_LIFEWATER_OASIS = 10,
	AP_LEVEL_PYRAMID_OF_THE_MOONS = 11,
	AP_LEVEL_PYRAMID_OF_SHADOWS = 12,
	AP_LEVEL_PYRAMID_OF_THE_GNOSTICENE_ANCEINTS = 13,
	AP_LEVEL_PYRAMID_OF_THE_FORBIDDEN = 14,
	AP_LEVEL_ISLE_OF_TAR = 15,
	AP_LEVEL_ISLE_OF_FIRE = 16,
	AP_LEVEL_WELL_OF_WISHES = 17,
	AP_LEVEL_BEAN_WITH_BACON_MEGAROCKET = 18
} AP_LevelId;

#endif